# ---------------------------------------------------------------------------------------------------------------------
# MkDocs Configuration
#
# This file defines the configuration for the project documentation site, including navigation structure,
# theme settings, plugins, markdown extensions, and build options.
#
# The documentation content referenced by this configuration is located in the `docs/` directory.
# All Markdown files, assets, and navigation entries should be maintained under that folder unless otherwise configured.
#
# Documentation: https://www.mkdocs.org/user-guide/configuration/
# ---------------------------------------------------------------------------------------------------------------------
site_name: WordPress REST API Client for Java
site_description: wp-rest-client is an open-source WordPress REST API client for Java. It provides a modern, type-safe Java API for interacting with the WordPress REST API, including posts, pages, media, categories, tags, users and custom endpoints.
site_url: https://evisentin.github.io/wp-rest-client/
repo_url: https://github.com/evisentin/wp-rest-client
# ---------------------------------------------------------------------------------------------------------------------
extra:
  social:
    - icon: fontawesome/solid/book
      link: https://javadoc.io/doc/io.github.evisentin/wp-rest-client
      name: Javadoc
# ---------------------------------------------------------------------------------------------------------------------
extra_css:
  - assets/stylesheets/extra.css
# ---------------------------------------------------------------------------------------------------------------------
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting_started/installation.md
      - Quick Start: getting_started/quick-start.md
      - Authentication: getting_started/authentication.md
  - Supported WP REST APIs: reference/supported-apis.md
  - Development:
      - Architecture: development/architecture.md
      - Contributing: development/contributing.md
      - Developer Setup: development/developer-setup.md
  - Use cases:
      - miniOrange REST API Authentication Plugin: use_cases/miniorange/miniorange-rest-api-authentication-plugin.md
  - Samples:
      - Introduction: samples/index.md
      - Category Operations: samples/category_operations.md
      - Page Operations: samples/page_operations.md
      - Post Operations: samples/post_operations.md
      - Taxonomy Operations: samples/taxonomy_operations.md
  - Test Coverage: test_coverage.md
  - License: license.md
# ---------------------------------------------------------------------------------------------------------------------
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
      toc_depth: "2-4"
# ---------------------------------------------------------------------------------------------------------------------
theme:
  features:
    - navigation.instant
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
# ---------------------------------------------------------------------------------------------------------------------
