package io.github.evisentin.wordpress.rest.client.samples.code.posts;

import io.github.evisentin.wordpress.rest.client.domain.WpRestClient;
import io.github.evisentin.wordpress.rest.client.domain.model.WpPost;
import io.github.evisentin.wordpress.rest.client.domain.model.enums.WpOpenClosed;
import io.github.evisentin.wordpress.rest.client.domain.model.requests.WpPostCreateUpdateRequest;
import io.github.evisentin.wordpress.rest.client.samples.code.SampleClientBuilder;

import static io.github.evisentin.wordpress.rest.client.domain.model.enums.WpPostStatus.PUBLISH;
import static io.github.evisentin.wordpress.rest.client.samples.code.SampleClientBuilder.AuthenticationType.BASIC_AUTH;
import static io.github.evisentin.wordpress.rest.client.samples.code.SampleClientBuilder.Implementation.APACHE;

/**
 * Demonstrates how to create a new WordPress post.
 * <p>
 * This sample illustrates how to:
 * <ul>
 *     <li>Create a {@link WpRestClient}.</li>
 *     <li>Build a {@link WpPostCreateUpdateRequest} using the builder API.</li>
 *     <li>Set common post attributes such as title, content, status, author, slug, excerpt,
 *     comment status, and ping status.</li>
 *     <li>Create the post using the WordPress REST API.</li>
 *     <li>Access the returned {@link WpPost} instance.</li>
 * </ul>
 * <p>
 * The request intentionally sets a number of optional fields to demonstrate the available customization options.
 * Most of these attributes are optional and, if omitted, WordPress automatically supplies sensible defaults where
 * applicable (for example, the slug, excerpt, and current authenticated user as the author).
 * <p>
 * Before running this sample, configure the connection details in {@link SampleClientBuilder} so they match your
 * WordPress installation.
 */
public class CreatePost {
    public static void main(String[] args) {

        // Choose the desired HTTP client implementation and authentication mechanism.
        //
        // Supported combinations:
        //   buildClientFor(BASIC_AUTH, APACHE)
        //   buildClientFor(JWT,        APACHE)
        //   buildClientFor(BASIC_AUTH, OK_HTTP)
        //   buildClientFor(JWT,        OK_HTTP)
        final WpRestClient restClient = SampleClientBuilder.buildClientFor(BASIC_AUTH, APACHE);

        WpPostCreateUpdateRequest createRequest =
                WpPostCreateUpdateRequest.builder()
                                         .withTitle("The title of my post")
                                         .withStatus(PUBLISH) // we want to create and publish it immediately
                                         .withContent("""
                                                 Lorem ipsum dolor sit amet consectetur adipiscing elit.
                                                 
                                                 Quisque faucibus ex sapien vitae pellentesque sem placerat.
                                                 
                                                 In id cursus mi pretium tellus duis convallis.
                                                 """)
                                         .withAuthorId(100L) // if not specified, the current user's ID is put automatically by WordPress
                                         .withCommentStatus(WpOpenClosed.OPEN) // not mandatory, here to show it
                                         .withPingStatus(WpOpenClosed.CLOSED) // not mandatory, here to show it
                                         .withSlug("something") // generated by WordPress if not passed
                                         .withExcerpt("Lorem ipsum dolor sit") // generated by WordPress if not passed
                                         // see WpPostCreateUpdateRequest Javadoc for other attributes
                                         .build();

        final WpPost wpPost = restClient.posts().create(createRequest);

        System.out.println("Post created with id=" + wpPost.getId());
    }
}
