package io.github.evisentin.wordpress.rest.client.samples.code.pages;

import io.github.evisentin.wordpress.rest.client.domain.WpRestClient;
import io.github.evisentin.wordpress.rest.client.domain.model.WpPage;
import io.github.evisentin.wordpress.rest.client.domain.model.enums.WpOpenClosed;
import io.github.evisentin.wordpress.rest.client.domain.model.requests.WpPageCreateUpdateRequest;
import io.github.evisentin.wordpress.rest.client.samples.code.SampleClientBuilder;

import static io.github.evisentin.wordpress.rest.client.domain.model.enums.WpPageStatus.PUBLISH;
import static io.github.evisentin.wordpress.rest.client.samples.code.SampleClientBuilder.AuthenticationType.BASIC_AUTH;
import static io.github.evisentin.wordpress.rest.client.samples.code.SampleClientBuilder.Implementation.APACHE;

/**
 * Demonstrates how to create a new WordPress page.
 * <p>
 * This sample illustrates how to:
 * <ul>
 *     <li>Create a {@link WpRestClient}.</li>
 *     <li>Build a {@link WpPageCreateUpdateRequest} using the builder API.</li>
 *     <li>Set common page attributes such as title, content, status, author, slug, excerpt,
 *     comment status, and ping status.</li>
 *     <li>Create the page using the WordPress REST API.</li>
 *     <li>Access the returned {@link WpPage} instance.</li>
 * </ul>
 * <p>
 * The request intentionally sets a number of optional fields to demonstrate the available customization options.
 * Most of these attributes are optional and, if omitted, WordPress automatically supplies sensible defaults where
 * applicable (for example, the slug, excerpt, and current authenticated user as the author).
 * <p>
 * Before running this sample, configure the connection details in {@link SampleClientBuilder} so they match your
 * WordPress installation.
 */
public class CreatePage {
    public static void main(String[] args) {

        // Choose the desired HTTP client implementation and authentication mechanism.
        //
        // Supported combinations:
        //   buildClientFor(BASIC_AUTH, APACHE)
        //   buildClientFor(JWT,        APACHE)
        //   buildClientFor(BASIC_AUTH, OK_HTTP)
        //   buildClientFor(JWT,        OK_HTTP)
        final WpRestClient restClient = SampleClientBuilder.buildClientFor(BASIC_AUTH, APACHE);

        WpPageCreateUpdateRequest createRequest =
                WpPageCreateUpdateRequest.builder()
                                         .withTitle("The title of my page")
                                         .withStatus(PUBLISH) // we want to create and publish it immediately
                                         .withContent("""
                                                 Lorem ipsum dolor sit amet consectetur adipiscing elit.
                                                 
                                                 Quisque faucibus ex sapien vitae pellentesque sem placerat.
                                                 
                                                 In id cursus mi pretium tellus duis convallis.
                                                 """)
                                         .withAuthorId(100L) // if not specified, the current user's ID is put automatically by WordPress
                                         .withCommentStatus(WpOpenClosed.OPEN) // not mandatory, here to show it
                                         .withPingStatus(WpOpenClosed.CLOSED) // not mandatory, here to show it
                                         .withSlug("something") // generated by WordPress if not passed
                                         .withExcerpt("Lorem ipsum dolor sit") // generated by WordPress if not passed
                                         // see WpPageCreateUpdateRequest Javadoc for other attributes
                                         .build();

        final WpPage wpPage = restClient.pages().create(createRequest);

        System.out.println("Page created with id=" + wpPage.getId());
    }
}
